### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by gterzian** [arbitraryco/base64-encode#1]
Thanks a lot for the great work and the PKG installer, could you pls add instructions for uninstall too? cheers

**Comment by jkosoy** [comment]
Yes, of course!

To uninstall, simply delete /Library/Services/Base64 Encode.service. It'll ask for your admin password. The app isn't storing any data and doesn't have any dependancies so no harm will come to you deleting it that way.

 Will add this to the README shortly.

**Comment by gterzian** [comment]
thanks! And great work by the way, I was just wondering how to uninstall it that's all :)

**Comment by jkosoy** [comment]
Updated the README with these instructions, as promised.
